package id.co.indocyber.guessgame;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class GuessingGame extends javax.swing.JFrame {
     
    //  diganti word model      String basicWord; // buat kata yang mau di tebak
    WordModel modelWord;
//diganti word model    String[] bankSoal = {"Pondok Indah" , "Sudirman" , "Tugu Tani", "Citos", "Gandaria City"};; // ini kumpulan soalnya di simpen di bank soal
//    WordModel soal1 = new WordModel("Pondok Indah", "Daerah di jakarta selatan");
//    WordModel soal2 = new WordModel("Sudirman", "Nama jendral dan jadi jalan utama di Jakarta");
//    WordModel soal3 = new WordModel("Tugu tani", "Patung dekat monas");
//    WordModel soal4 = new WordModel("Citos", "Mall di selatan jakarta");
//    WordModel soal5 = new WordModel("Gandaria city", "Mall anak muda");
//    
//    WordModel[] bankSoal = {soal1, soal2, soal3, soal4, soal5};
    List<WordModel> bankSoal;

    /**
     * Creates new form GuessingGame
     */
    public GuessingGame() throws IOException {
        //bankSoal.add(soal1);
//        bankSoal = WordQuestionGenerator.createQuestionInCollection();
        bankSoal = WordQuestionGenerator.createQuestionFromFile("C:/JAVA_LATIHAN/question.txt");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        soalTextField = new javax.swing.JTextField();
        jawabanTextField = new javax.swing.JTextField();
        checkAnswerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mulaiButton = new javax.swing.JButton();
        jawabanLabel = new javax.swing.JLabel();
        kotaComboBox = new javax.swing.JComboBox<>();
        hintButton = new javax.swing.JButton();
        hintLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        soalTextField.setEditable(false);
        soalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soalTextFieldActionPerformed(evt);
            }
        });

        checkAnswerButton.setText("Periksa");
        checkAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnswerButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Jawaban :");

        mulaiButton.setText("MULAI");
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });

        jawabanLabel.setText("Belum ada jawaban");

        kotaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jakarta", "Depok", "Bogor" }));

        hintButton.setText("Bantu Dong");
        hintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonActionPerformed(evt);
            }
        });

        hintLabel.setText("Hint :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(soalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jawabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkAnswerButton)
                            .addComponent(jLabel1)
                            .addComponent(jawabanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mulaiButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kotaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hintButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(hintLabel)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mulaiButton)
                    .addComponent(kotaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hintButton))
                .addGap(21, 21, 21)
                .addComponent(soalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hintLabel)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jawabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkAnswerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jawabanLabel)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soalTextFieldActionPerformed

    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        int soalIndex = (int) Math.floor(Math.random() * bankSoal.size()); // floor dipake biar index 0 nya bisa ke ambil, kalo pake ceil index 0 gakkan pernah dapet
        modelWord = bankSoal.get(soalIndex); //naro salah satu kata yang ada di bank soal ke variabel basicWord
        soalTextField.setText(modelWord.acakHuruf());

//        basicWord = basicWord.toUpperCase(); // to uppercase berfungsi untuk merubah huruf kecil menjadi kapital
//        String[] arrayOfWord = basicWord.split(""); //split digunakan untuk mengacak huruf dari susunan yang telah di definisikan
//        // isi arrayofword = (b,u,a,y,a)
//        
//        //System.out.println("Huruf ke 2: " + arrayOfWord(1));
//        
//        for (int i = 0; i < arrayOfWord.length; i++){ //buat ngesplit huruf yang di arrayOfWord
//            //System.out.println(arrayOfWord[i]);
//        }
//        
//        Arrays.sort(arrayOfWord); //ngurutin si arrayofword
//        StringBuilder sb = new StringBuilder(); // buat looping bikin penampung string dari beberapa kata
//        System.out.println("\nSetelah disort\n");
//        
//        for (int i = 0; i <arrayOfWord.length; i++){ // buat looping nge append atau nambahin huruf per huruf nya biar jadi satu kata
//            System.out.println(arrayOfWord[i]);
//            
//            sb.append(arrayOfWord[i]); //append buat nambahin si string buiilder sama beberapa kata
//        }
//        
//        String soal = sb.toString();
//        System.out.println("soal yang harus di jawab: " + soal.trim());
//        char[] alphabets = basicWord.toCharArray();
//        
//        soalTextField.setText(soal.trim());
    }//GEN-LAST:event_mulaiButtonActionPerformed

    private void checkAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnswerButtonActionPerformed
       try{
        String jawaban = jawabanTextField.getText().trim();
        modelWord.setJawaban(jawaban);
        if(modelWord.cekJawaban()){
            jawabanLabel.setText("Jawaban anda benar");
        } else {
            jawabanLabel.setText("Jawaban anda salah, silahkan coba lagi");
        }
       } catch (Exception e){
           JOptionPane.showMessageDialog(rootPane, "Anda belum mencet tombol mulai bosque");
       }
    }//GEN-LAST:event_checkAnswerButtonActionPerformed

    private void hintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonActionPerformed
        try{
        hintLabel.setText(modelWord.getHint());
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Anda belum mencet tombol mulai bosque");
        }
    }//GEN-LAST:event_hintButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GuessingGame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GuessingGame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkAnswerButton;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel jawabanLabel;
    private javax.swing.JTextField jawabanTextField;
    private javax.swing.JComboBox<String> kotaComboBox;
    private javax.swing.JButton mulaiButton;
    private javax.swing.JTextField soalTextField;
    // End of variables declaration//GEN-END:variables
}
